# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'calculadora.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSplitter, QWidget)

class Ui_Calculadora(object):
    def setupUi(self, Calculadora):
        if not Calculadora.objectName():
            Calculadora.setObjectName(u"Calculadora")
        Calculadora.resize(385, 170)
        self.centralwidget = QWidget(Calculadora)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 10, 261, 51))
        font = QFont()
        font.setPointSize(35)
        self.label_2.setFont(font)
        self.splitter_6 = QSplitter(self.centralwidget)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setGeometry(QRect(20, 60, 351, 98))
        font1 = QFont()
        font1.setPointSize(12)
        self.splitter_6.setFont(font1)
        self.splitter_6.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_4 = QSplitter(self.splitter_6)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setFont(font1)
        self.splitter_4.setOrientation(Qt.Orientation.Vertical)
        self.entrada1 = QLineEdit(self.splitter_4)
        self.entrada1.setObjectName(u"entrada1")
        self.entrada1.setMinimumSize(QSize(0, 30))
        self.entrada1.setMaximumSize(QSize(16777215, 30))
        self.entrada1.setFont(font1)
        self.splitter_4.addWidget(self.entrada1)
        self.entrada2 = QLineEdit(self.splitter_4)
        self.entrada2.setObjectName(u"entrada2")
        self.entrada2.setMinimumSize(QSize(0, 30))
        self.entrada2.setMaximumSize(QSize(16777215, 30))
        self.entrada2.setFont(font1)
        self.splitter_4.addWidget(self.entrada2)
        self.resultado = QLabel(self.splitter_4)
        self.resultado.setObjectName(u"resultado")
        self.resultado.setMinimumSize(QSize(0, 30))
        self.resultado.setMaximumSize(QSize(16777215, 30))
        self.resultado.setFont(font1)
        self.splitter_4.addWidget(self.resultado)
        self.splitter_6.addWidget(self.splitter_4)
        self.splitter_5 = QSplitter(self.splitter_6)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setFont(font1)
        self.splitter_5.setOrientation(Qt.Orientation.Vertical)
        self.splitter_3 = QSplitter(self.splitter_5)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setFont(font1)
        self.splitter_3.setOrientation(Qt.Orientation.Horizontal)
        self.splitter = QSplitter(self.splitter_3)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setFont(font1)
        self.splitter.setOrientation(Qt.Orientation.Vertical)
        self.btsuma = QPushButton(self.splitter)
        self.btsuma.setObjectName(u"btsuma")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btsuma.sizePolicy().hasHeightForWidth())
        self.btsuma.setSizePolicy(sizePolicy)
        self.btsuma.setMinimumSize(QSize(60, 30))
        self.btsuma.setMaximumSize(QSize(60, 30))
        self.btsuma.setFont(font1)
        self.splitter.addWidget(self.btsuma)
        self.btresta = QPushButton(self.splitter)
        self.btresta.setObjectName(u"btresta")
        sizePolicy.setHeightForWidth(self.btresta.sizePolicy().hasHeightForWidth())
        self.btresta.setSizePolicy(sizePolicy)
        self.btresta.setMinimumSize(QSize(60, 30))
        self.btresta.setMaximumSize(QSize(60, 30))
        self.btresta.setFont(font1)
        self.splitter.addWidget(self.btresta)
        self.splitter_3.addWidget(self.splitter)
        self.splitter_2 = QSplitter(self.splitter_3)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setFont(font1)
        self.splitter_2.setOrientation(Qt.Orientation.Vertical)
        self.btmulti = QPushButton(self.splitter_2)
        self.btmulti.setObjectName(u"btmulti")
        sizePolicy.setHeightForWidth(self.btmulti.sizePolicy().hasHeightForWidth())
        self.btmulti.setSizePolicy(sizePolicy)
        self.btmulti.setMinimumSize(QSize(60, 30))
        self.btmulti.setMaximumSize(QSize(60, 30))
        self.btmulti.setFont(font1)
        self.splitter_2.addWidget(self.btmulti)
        self.btdivi = QPushButton(self.splitter_2)
        self.btdivi.setObjectName(u"btdivi")
        sizePolicy.setHeightForWidth(self.btdivi.sizePolicy().hasHeightForWidth())
        self.btdivi.setSizePolicy(sizePolicy)
        self.btdivi.setMinimumSize(QSize(60, 30))
        self.btdivi.setMaximumSize(QSize(60, 30))
        self.btdivi.setFont(font1)
        self.splitter_2.addWidget(self.btdivi)
        self.splitter_3.addWidget(self.splitter_2)
        self.splitter_5.addWidget(self.splitter_3)
        self.btsalida = QPushButton(self.splitter_5)
        self.btsalida.setObjectName(u"btsalida")
        sizePolicy.setHeightForWidth(self.btsalida.sizePolicy().hasHeightForWidth())
        self.btsalida.setSizePolicy(sizePolicy)
        self.btsalida.setMaximumSize(QSize(125, 16777215))
        self.btsalida.setFont(font1)
        self.splitter_5.addWidget(self.btsalida)
        self.splitter_6.addWidget(self.splitter_5)
        Calculadora.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculadora)

        QMetaObject.connectSlotsByName(Calculadora)
    # setupUi

    def retranslateUi(self, Calculadora):
        Calculadora.setWindowTitle(QCoreApplication.translate("Calculadora", u"MainWindow", None))
        self.label_2.setText(QCoreApplication.translate("Calculadora", u"Calculadora", None))
        self.resultado.setText("")
        self.btsuma.setText(QCoreApplication.translate("Calculadora", u"+", None))
        self.btresta.setText(QCoreApplication.translate("Calculadora", u"-", None))
        self.btmulti.setText(QCoreApplication.translate("Calculadora", u"*", None))
        self.btdivi.setText(QCoreApplication.translate("Calculadora", u"/", None))
        self.btsalida.setText(QCoreApplication.translate("Calculadora", u"Salir", None))
    # retranslateUi

